//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

public class Second {
    public static void main(String[] args) {
        int sum;
        int a ,b ;
        a = 1;
        b = 2;
        sum = 0;

        while (a <= 4000000 & b <= 4000000){

            //We add the numbers that can devide by two because it wants this
            if (a % 2 == 0){
                sum = sum + a;
            }
            if (b % 2 == 0){
                sum = sum + b;
            }
            a = a + b;
            b = a + b;
        }
        System.out.println(sum);
    }
}
