# Short Question Description: How many distinct terms are in the sequence generated by a^b for 2 =< a =< 100 and  2 =< b =< 100?
# Author: @SelimGunal
# Finished on 06.07.2023

numbers = []
for i in range(2, 101):
    for x in range(2, 101):
        currentNumber = str(i**x)

        if not(currentNumber in numbers):
            numbers.append(currentNumber)

print(len(numbers))
